[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "textcleaner"
version = "0.1.0"
description = "A text cleaning utility for NLP tasks."
readme = "README.md"
requires-python = ">=3.6"